### Simple, Multiple, and Logistic Regression Analysis on CalCOFI oceanographic data

In [1]:
# Importing required packages
import pandas as pd

In [4]:
# Reading in data tables from https://calcofi.org/data/oceanographic-data/bottle-database/
df_bottle = pd.read_csv('CalCOFI_Database/194903-202101_Bottle.csv', encoding='unicode_escape')
df_bottle

C:\Users\copel\AppData\Local\Temp\ipykernel_7968\1879365886.py:2: DtypeWarning: Columns (47,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bottle = pd.read_csv('CalCOFI_Database/194903-202101_Bottle.csv', encoding='unicode_escape')

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,R_DYNHT,R_Nuts,R_Oxy_µmol/Kg,DIC1,DIC2,TA1,TA2,pH1,pH2,DIC Quality Comment
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0,10.500,33.4400,NaN,25.64900,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8,10.460,33.4400,NaN,25.65600,NaN,...,0.010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10,10.460,33.4370,NaN,25.65400,NaN,...,0.020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19,10.450,33.4200,NaN,25.64300,NaN,...,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20,10.450,33.4210,NaN,25.64300,NaN,...,0.040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894475,35599,894476,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0500A-7,500,5.992,34.2128,0.539,26.94277,7.74,...,1.058,0.00,23.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894476,35599,894477,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0515A-3,515,5.911,34.2168,0.459,26.95630,6.58,...,1.080,0.00,19.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894477,35600,894478,093.4 026.4,20-2101RL-MX-016-0746-09340264-0000A-7,0,14.526,33.5682,6.352,24.98482,109.64,...,0.000,0.01,276.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894478,35600,894479,093.4 026.4,20-2101RL-MX-016-0746-09340264-0002A-3,2,14.526,33.5682,6.352,24.97098,109.64,...,0.006,0.00,276.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894479,35600,894480,093.4 026.4,20-2101RL-MX-016-0746-09340264-0009A-3,9,13.914,33.6199,5.577,25.13973,95.09,...,0.026,0.12,242.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
bottle = df_bottle.copy()
bottle.dropna(axis='columns', thresh=int(bottle.shape[0]*.80), inplace=True)
bottle.dropna(inplace=True)
bottle

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,RecInd,...,S_prec,NH3q,C14A1q,C14A2q,DarkAq,MeanAq,R_Depth,R_Temp,R_Sal,R_DYNHT
2160,71,2161,044.0 048.5,19-4904CR-HY-087-0606-04400485-0000B-3,0,10.300,33.0300,5.900,25.36400,3,...,2.0,9.0,9.0,9.0,9.0,9.0,0.0,10.30,260.2,0.000
2162,71,2163,044.0 048.5,19-4904CR-HY-087-0606-04400485-0010A-7,10,10.290,32.9510,6.040,25.30400,7,...,3.0,9.0,9.0,9.0,9.0,9.0,10.0,10.29,266.1,0.020
2163,71,2164,044.0 048.5,19-4904CR-HY-087-0606-04400485-0015A-3,15,10.290,32.9900,6.060,25.33500,3,...,2.0,9.0,9.0,9.0,9.0,9.0,15.0,10.29,263.3,0.040
2164,71,2165,044.0 048.5,19-4904CR-HY-087-0606-04400485-0020A-7,20,10.330,33.0050,6.040,25.33900,7,...,3.0,9.0,9.0,9.0,9.0,9.0,20.0,10.33,262.9,0.050
2165,71,2166,044.0 048.5,19-4904CR-HY-087-0606-04400485-0030A-7,30,10.390,33.0540,6.010,25.36800,7,...,3.0,9.0,9.0,9.0,9.0,9.0,30.0,10.39,260.4,0.070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894473,35599,894474,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0381A-3,381,6.864,34.0847,1.342,26.72612,3,...,3.0,4.0,9.0,9.0,9.0,9.0,384.0,6.83,137.2,0.911
894474,35599,894475,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0400A-7,400,6.627,34.1185,1.199,26.78473,7,...,3.0,4.0,9.0,9.0,9.0,9.0,403.0,6.59,131.8,0.932
894475,35599,894476,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0500A-7,500,5.992,34.2128,0.539,26.94277,7,...,3.0,4.0,9.0,9.0,9.0,9.0,504.0,5.95,117.7,1.058
894476,35599,894477,093.3 0120.0,20-2101RL-MX-019-0552-09331200-0515A-3,515,5.911,34.2168,0.459,26.95630,3,...,3.0,4.0,9.0,9.0,9.0,9.0,519.0,5.87,116.6,1.080
894478,35600,894479,093.4 026.4,20-2101RL-MX-016-0746-09340264-0002A-3,2,14.526,33.5682,6.352,24.97098,3,...,3.0,4.0,9.0,9.0,9.0,9.0,2.0,14.53,297.6,0.006

In [21]:
# bottle.to_csv("194903-202101_Bottle2.csv")
int(bottle.shape[0]*.95)

718484

In [26]:
df_cast = pd.read_csv('CalCOFI_Database/194903-202101_Cast.csv', encoding='unicode_escape')
df_cast.head()
# df_cast.describe()

C:\Users\copel\AppData\Local\Temp\ipykernel_7968\409792041.py:1: DtypeWarning: Columns (38,39,42,43,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cast = pd.read_csv('CalCOFI_Database/194903-202101_Cast.csv', encoding='unicode_escape')

,Cst_Cnt,Cruise_ID,Cruise,Cruz_Sta,DbSta_ID,Cast_ID,Sta_ID,Quarter,Sta_Code,Distance,...,Wind_Spd,Barometer,Dry_T,Wet_T,Wea,Cloud_Typ,Cloud_Amt,Visibility,Secchi,ForelU
0,1,1949-03-01-C-31CR,194903,19490305400560,5400560,19-4903CR-HY-060-0930-05400560,054.0 056.0,1,NST,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
1,2,1949-03-01-C-31CR,194903,19490305200750,5200750,19-4903CR-HY-060-2112-05200750,052.0 075.0,1,NST,NaN,...,5.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
2,3,1949-03-01-C-31CR,194903,19490305100850,5100850,19-4903CR-HY-061-0354-05100850,051.0 085.0,1,NST,NaN,...,5.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN
3,4,1949-03-01-C-31CR,194903,19490305000950,5000950,19-4903CR-HY-061-1042-05000950,050.0 095.0,1,NST,NaN,...,8.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
4,5,1949-03-01-C-31CR,194903,19490305001040,5001040,19-4903CR-HY-061-1706-05001040,050.0 104.0,1,NST,NaN,...,13.0,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN

In [33]:
df = pd.merge(df_bottle, df_cast)
# df = df.astype({"Year": 'int'})
df
# df.nunique()
# df.dtypes

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,Wind_Spd,Barometer,Dry_T,Wet_T,Wea,Cloud_Typ,Cloud_Amt,Visibility,Secchi,ForelU
0,1,1,054.0 056.0,19-4903CR-HY-060-0930-05400560-0000A-3,0,10.500,33.4400,NaN,25.64900,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
1,1,2,054.0 056.0,19-4903CR-HY-060-0930-05400560-0008A-3,8,10.460,33.4400,NaN,25.65600,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
2,1,3,054.0 056.0,19-4903CR-HY-060-0930-05400560-0010A-7,10,10.460,33.4370,NaN,25.65400,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
3,1,4,054.0 056.0,19-4903CR-HY-060-0930-05400560-0019A-3,19,10.450,33.4200,NaN,25.64300,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
4,1,5,054.0 056.0,19-4903CR-HY-060-0930-05400560-0020A-7,20,10.450,33.4210,NaN,25.64300,NaN,...,18.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893590,35596,894405,093.3 090.0,20-2101RL-MX-018-1206-09330900-0500A-7,500,5.964,34.2703,0.357,26.99172,5.12,...,12.0,1011.9,16.0,14.8,NaN,NaN,NaN,NaN,NaN,NaN
893591,35596,894406,093.3 090.0,20-2101RL-MX-018-1206-09330900-0517A-3,517,5.859,34.2642,0.339,27.00023,4.85,...,12.0,1011.9,16.0,14.8,NaN,NaN,NaN,NaN,NaN,NaN
893592,35600,894478,093.4 026.4,20-2101RL-MX-016-0746-09340264-0000A-7,0,14.526,33.5682,6.352,24.98482,109.64,...,12.0,1015.2,16.5,12.0,NaN,NaN,NaN,NaN,NaN,NaN
893593,35600,894479,093.4 026.4,20-2101RL-MX-016-0746-09340264-0002A-3,2,14.526,33.5682,6.352,24.97098,109.64,...,12.0,1015.2,16.5,12.0,NaN,NaN,NaN,NaN,NaN,NaN
893594,35600,894480,093.4 026.4,20-2101RL-MX-016-0746-09340264-0009A-3,9,13.914,33.6199,5.577,25.13973,95.09,...,12.0,1015.2,16.5,12.0,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df.dropna(axis='columns', thresh=int(bottle.shape[0]*.80), inplace=True)# df = df.dropna()
df.dropna(inplace=True)
df

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,Data_Type,Event_Num,Orig_Sta_ID,Cruz_Num,Wind_Dir,Wind_Spd,Barometer,Dry_T,Wet_T,Wea
375187,13972,375188,093.3 028.0,19-6404AX-HY-102-0342-09330280-0000B-3,0,14.68,33.736,6.89,25.067,119.4,...,HY,1695.0,93 28,6404,22.0,2.0,1015.2,15.0,12.8,1.0
375188,13972,375189,093.3 028.0,19-6404AX-HY-102-0342-09330280-0010A-3,10,13.64,33.725,6.86,25.277,116.4,...,HY,1695.0,93 28,6404,22.0,2.0,1015.2,15.0,12.8,1.0
375189,13972,375190,093.3 028.0,19-6404AX-HY-102-0342-09330280-0020A-7,20,12.65,33.718,5.57,25.470,92.6,...,HY,1695.0,93 28,6404,22.0,2.0,1015.2,15.0,12.8,1.0
375190,13972,375191,093.3 028.0,19-6404AX-HY-102-0342-09330280-0030A-3,30,11.74,33.736,4.06,25.657,66.2,...,HY,1695.0,93 28,6404,22.0,2.0,1015.2,15.0,12.8,1.0
375191,13972,375192,093.3 028.0,19-6404AX-HY-102-0342-09330280-0045A-3,45,10.61,33.841,3.25,25.943,51.7,...,HY,1695.0,93 28,6404,22.0,2.0,1015.2,15.0,12.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817760,32580,817761,070.0 055.0,20-1101NM-MX-031-1553-07000550-0250A-7,250,8.03,34.108,1.45,26.573,21.8,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817762,32580,817763,070.0 055.0,20-1101NM-MX-031-1553-07000550-0300A-7,300,7.58,34.166,1.12,26.685,16.7,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817765,32580,817766,070.0 055.0,20-1101NM-MX-031-1553-07000550-0400A-7,400,6.95,34.191,0.72,26.794,10.6,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817767,32580,817768,070.0 055.0,20-1101NM-MX-031-1553-07000550-0500A-7,500,6.03,34.255,0.40,26.966,5.7,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
830772,33073,830773,093.3 028.0,20-1207OS-MX-185-1506-09330280-0000B-7,0,18.05,33.586,6.40,24.178,118.4,...,MX,12.0,93.3 28.0,1207,16.0,5.0,1013.0,12.6,12.0,2.0

In [41]:
df.tail(5000)

,Cst_Cnt,Btl_Cnt,Sta_ID,Depth_ID,Depthm,T_degC,Salnty,O2ml_L,STheta,O2Sat,...,Data_Type,Event_Num,Orig_Sta_ID,Cruz_Num,Wind_Dir,Wind_Spd,Barometer,Dry_T,Wet_T,Wea
401500,15055,401501,086.7 080.0,19-6612JD-HY-343-0836-08670800-0000B-3,0,15.90,33.438,5.74,24.570,101.8,...,HY,2117.0,87 80,6612,32.0,18.0,1021.0,14.4,11.8,1.0
401501,15055,401502,086.7 080.0,19-6612JD-HY-343-0836-08670800-0010A-3,10,15.86,33.438,5.76,24.579,102.0,...,HY,2117.0,87 80,6612,32.0,18.0,1021.0,14.4,11.8,1.0
401503,15055,401504,086.7 080.0,19-6612JD-HY-343-0836-08670800-0030A-3,30,15.88,33.439,5.74,24.576,101.7,...,HY,2117.0,87 80,6612,32.0,18.0,1021.0,14.4,11.8,1.0
401505,15055,401506,086.7 080.0,19-6612JD-HY-343-0836-08670800-0061A-3,61,12.40,33.423,4.70,25.290,77.5,...,HY,2117.0,87 80,6612,32.0,18.0,1021.0,14.4,11.8,1.0
401506,15055,401507,086.7 080.0,19-6612JD-HY-343-0836-08670800-0069A-3,69,11.28,33.408,4.42,25.488,71.2,...,HY,2117.0,87 80,6612,32.0,18.0,1021.0,14.4,11.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817760,32580,817761,070.0 055.0,20-1101NM-MX-031-1553-07000550-0250A-7,250,8.03,34.108,1.45,26.573,21.8,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817762,32580,817763,070.0 055.0,20-1101NM-MX-031-1553-07000550-0300A-7,300,7.58,34.166,1.12,26.685,16.7,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817765,32580,817766,070.0 055.0,20-1101NM-MX-031-1553-07000550-0400A-7,400,6.95,34.191,0.72,26.794,10.6,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
817767,32580,817768,070.0 055.0,20-1101NM-MX-031-1553-07000550-0500A-7,500,6.03,34.255,0.40,26.966,5.7,...,MX,852.0,70.0 55.0,1101,26.0,16.0,1023.2,13.5,11.0,1.0
830772,33073,830773,093.3 028.0,20-1207OS-MX-185-1506-09330280-0000B-7,0,18.05,33.586,6.40,24.178,118.4,...,MX,12.0,93.3 28.0,1207,16.0,5.0,1013.0,12.6,12.0,2.0

In [42]:
df.tail(5000).to_csv("df.csv")